# Generated by Django 3.2.12 on 2022-05-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_num',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='stud_in_group',
            new_name='students_amount',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='social_url',
            field=models.CharField(default='', max_length=80),
        ),
    ]
